$ANSIBLE_VAULT;1.1;AES256
37333732663439366235343230393465383736623739663833313230346264313530326261323165
6331316337366561636534356162616161313931316334380a303862396436326463646266663865
38643038653162356131306334383334393130333639666337643836373866616331636263633935
3364383933633837390a363133343261363339666163316239616464376639303631656461633635
61666231663561366236393162366436616163353464396130636539633937653261363339373939
38636336326530316639386462326136623036373763386564623238376539353630643539623265
366265373336666264303937663039666432
